language: php

services:
    - docker

before_install:
   - cp .env.example .env
   - docker-compose up -d --build
   - mkdir -m 777 vendor
   - docker-compose run app composer config -g github-oauth.github.com 79cfdef8edaab0657e3fa0df540ec13f38219a7a
   - docker-compose run app composer install
   - docker-compose run app php artisan key:generate
   - docker-compose run app php artisan jwt:secret
   - docker-compose run app php artisan migrate --seed --env=testing
   
script:
   - docker-compose run app  ./vendor/bin/phpcbf app/ --standard=PSR2
   - docker-compose run app vendor/bin/phpunit
