# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  managment-mysql-data:
    driver: local

  # Redis Data
  managment-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: managment-mysql
    volumes:
      - managment-mysql-data:/var/lib/mysql
    ports:
      - "4000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=managment
      - MYSQL_DATABASE=managment
      - MYSQL_USER=managment
      - MYSQL_PASSWORD=managment

  # Redis
  cache:
    image: redis:4.0
    container_name: managment-redis
    command: --appendonly yes
    volumes:
      - managment-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: managment-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.2
    container_name: managment-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache